---
title: "ggplot Basics Refresher"
author: "Sean Huu Nguyen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,nycflights13,gapminder,socviz)
```

### Figure 3.13


```{r 3.13 plot}

p <- ggplot(data = gapminder,
            mapping = aes(x = gdpPercap,
                          y=lifeExp))
p + geom_point(alpha = 0.3) + 
  geom_smooth(method = "lm") +
  scale_x_log10(labels = scales::dollar) +
  labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")

```

### Figure 3.16

```{r 3.16 plot}
p <- ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp))
p + geom_point(mapping = aes(color = continent)) +
    geom_smooth(method = "loess") +
    scale_x_log10()
```

### Orignal graph

```{r Original Plot}

mpg %>%
  mutate(class = fct_reorder(class, hwy, .fun='median')) %>% 
  ggplot( aes(x=class, y=hwy, fill=class)) + 
    geom_boxplot() + 
    theme(legend.position="none") +
  labs(title = "Highway Miles per Gallon by Vehicle Classification", 
           x = "Vehicle Type",
           y = "Highway MPG" ) +
  theme(axis.title.x = element_text(margin = margin(t = 10)))


```



